In [3]:
import pandas as pd
df = pd.read_csv("../data/soc-redditHyperlinks-body.tsv", sep='\t')
df

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,PROPERTIES
0,leagueoflegends,teamredditteams,1u4nrps,2013-12-31 16:39:58,1,"345.0,298.0,0.75652173913,0.0173913043478,0.08..."
1,theredlion,soccer,1u4qkd,2013-12-31 18:18:37,-1,"101.0,98.0,0.742574257426,0.019801980198,0.049..."
2,inlandempire,bikela,1u4qlzs,2014-01-01 14:54:35,1,"85.0,85.0,0.752941176471,0.0235294117647,0.082..."
3,nfl,cfb,1u4sjvs,2013-12-31 17:37:55,1,"1124.0,949.0,0.772241992883,0.0017793594306,0...."
4,playmygame,gamedev,1u4w5ss,2014-01-01 02:51:13,1,"715.0,622.0,0.777622377622,0.00699300699301,0...."
...,...,...,...,...,...,...
286556,negareddit,debatefascism,68im20s,2017-04-30 16:31:26,1,"441.0,405.0,0.775510204082,0.0294784580499,0.0..."
286557,mildlynomil,justnomil,68imlas,2017-04-30 04:19:03,1,"2226.0,1855.0,0.786163522013,0.00224618149146,..."
286558,mmorpg,blackdesertonline,68ip5os,2017-04-30 16:54:08,1,"1100.0,909.0,0.778181818182,0.00181818181818,0..."
286559,electricskateboards,askreddit,68ipb2s,2017-04-30 16:41:53,1,"1876.0,1567.0,0.78144989339,0.00692963752665,0..."
286560,mgtow,dataisbeautiful,68ipeos,2017-04-30 16:52:59,1,"1129.0,975.0,0.795394154119,0.0150575730735,0...."

In [23]:
# Expand the properties column of lists into columns
import ast
df_expanded = df['PROPERTIES'].apply(ast.literal_eval).apply(pd.Series)

# List of column names for the expanded properties
column_names = [
    "Number of characters",
    "Number of characters without counting white space",
    "Fraction of alphabetical characters",
    "Fraction of digits",
    "Fraction of uppercase characters",
    "Fraction of white spaces",
    "Fraction of special characters, such as comma, exclamation mark, etc.",
    "Number of words",
    "Number of unique works",
    "Number of long words (at least 6 characters)",
    "Average word length",
    "Number of unique stopwords",
    "Fraction of stopwords",
    "Number of sentences",
    "Number of long sentences (at least 10 words)",
    "Average number of characters per sentence",
    "Average number of words per sentence",
    "Automated readability index",
    "Positive sentiment",
    "Negative sentiment",
    "Compound sentiment",
    "LIWC_Funct",
    "LIWC_Pronoun",
    "LIWC_Ppron",
    "LIWC_I",
    "LIWC_We",
    "LIWC_You",
    "LIWC_SheHe",
    "LIWC_They",
    "LIWC_Ipron",
    "LIWC_Article",
    "LIWC_Verbs",
    "LIWC_AuxVb",
    "LIWC_Past",
    "LIWC_Present",
    "LIWC_Future",
    "LIWC_Adverbs",
    "LIWC_Prep",
    "LIWC_Conj",
    "LIWC_Negate",
    "LIWC_Quant",
    "LIWC_Numbers",
    "LIWC_Swear",
    "LIWC_Social",
    "LIWC_Family",
    "LIWC_Friends",
    "LIWC_Humans",
    "LIWC_Affect",
    "LIWC_Posemo",
    "LIWC_Negemo",
    "LIWC_Anx",
    "LIWC_Anger",
    "LIWC_Sad",
    "LIWC_CogMech",
    "LIWC_Insight",
    "LIWC_Cause",
    "LIWC_Discrep",
    "LIWC_Tentat",
    "LIWC_Certain",
    "LIWC_Inhib",
    "LIWC_Incl",
    "LIWC_Excl",
    "LIWC_Percept",
    "LIWC_See",
    "LIWC_Hear",
    "LIWC_Feel",
    "LIWC_Bio",
    "LIWC_Body",
    "LIWC_Health",
    "LIWC_Sexual",
    "LIWC_Ingest",
    "LIWC_Relativ",
    "LIWC_Motion",
    "LIWC_Space",
    "LIWC_Time",
    "LIWC_Work",
    "LIWC_Achiev",
    "LIWC_Leisure",
    "LIWC_Home",
    "LIWC_Money",
    "LIWC_Relig",
    "LIWC_Death",
    "LIWC_Assent",
    "LIWC_Dissent",
    "LIWC_Nonflu",
    "LIWC_Filler"
]

# Set the column names for the expanded properties columns
df_expanded.columns = column_names

# Save expanded df to a new CSV file
df_expanded.to_csv("../data/redditHyperlinks-expanded_all.csv", index=False)

In [24]:
# Select only the columns we want to keep
columns_to_keep = ['Positive sentiment', 'Negative sentiment','Compound sentiment'] 
df_selected = df_expanded[columns_to_keep]
df = pd.concat([df.drop('PROPERTIES', axis=1), df_selected], axis=1)

# Save the dataframe to a new CSV file
df.to_csv("../data/redditHyperlinks-column-filtered.csv", index=False)

# Display the updated DataFrame
print(len(df))
df.head()

286561

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,Positive sentiment,Negative sentiment,Compound sentiment
0,leagueoflegends,teamredditteams,1u4nrps,2013-12-31 16:39:58,1,0.073,0.080,0.1748
1,theredlion,soccer,1u4qkd,2013-12-31 18:18:37,-1,0.472,0.000,0.5538
2,inlandempire,bikela,1u4qlzs,2014-01-01 14:54:35,1,0.000,0.000,0.0000
3,nfl,cfb,1u4sjvs,2013-12-31 17:37:55,1,0.153,0.026,0.9672
4,playmygame,gamedev,1u4w5ss,2014-01-01 02:51:13,1,0.139,0.039,0.8906

In [7]:
df = pd.read_csv("../data/redditHyperlinks-column-filtered.csv")
df

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,Positive sentiment,Negative sentiment,Compound sentiment
0,leagueoflegends,teamredditteams,1u4nrps,2013-12-31 16:39:58,1,0.073,0.080,0.1748
1,theredlion,soccer,1u4qkd,2013-12-31 18:18:37,-1,0.472,0.000,0.5538
2,inlandempire,bikela,1u4qlzs,2014-01-01 14:54:35,1,0.000,0.000,0.0000
3,nfl,cfb,1u4sjvs,2013-12-31 17:37:55,1,0.153,0.026,0.9672
4,playmygame,gamedev,1u4w5ss,2014-01-01 02:51:13,1,0.139,0.039,0.8906
...,...,...,...,...,...,...,...,...
286556,negareddit,debatefascism,68im20s,2017-04-30 16:31:26,1,0.056,0.079,-0.2593
286557,mildlynomil,justnomil,68imlas,2017-04-30 04:19:03,1,0.045,0.099,-0.9726
286558,mmorpg,blackdesertonline,68ip5os,2017-04-30 16:54:08,1,0.120,0.082,0.6052
286559,electricskateboards,askreddit,68ipb2s,2017-04-30 16:41:53,1,0.107,0.085,0.8071
286560,mgtow,dataisbeautiful,68ipeos,2017-04-30 16:52:59,1,0.068,0.075,-0.0643